/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mpm.gui;

import java.awt.Color;
import java.util.List;
import mpm.data.dao.DAOs;
import mpm.data.entities.User;
import mpm.main.MPM;

/**
 *
 * @author remo
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        
        initComponents();
        usernameInputField.setForeground(Color.GRAY);
        usernameInputField.setText("name@example.com ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        errorLabel = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        pnlLogin = new javax.swing.JPanel();
        inputLabel = new javax.swing.JLabel();
        usernameInputField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(740, 480));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(740, 480));

        errorLabel.setForeground(new java.awt.Color(255, 51, 51));

        logoLabel.setBackground(new java.awt.Color(253, 101, 8));
        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mpm/res/makerspaceLogo.png"))); // NOI18N
        logoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoLabel.setMaximumSize(new java.awt.Dimension(1380, 169));
        logoLabel.setOpaque(true);
        logoLabel.setPreferredSize(new java.awt.Dimension(640, 169));

        inputLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        inputLabel.setText("Username:");

        usernameInputField.setToolTipText("Enter your user name");
        usernameInputField.setNextFocusableComponent(loginButton);
        usernameInputField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameInputFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameInputFieldFocusLost(evt);
            }
        });
        usernameInputField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameInputFieldKeyPressed(evt);
            }
        });

        loginButton.setToolTipText("Click to login");
        loginButton.setLabel("Login");
        loginButton.setNextFocusableComponent(usernameInputField);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        btnRegister.setText("Register");
        btnRegister.setToolTipText("Click to register");
        btnRegister.setNextFocusableComponent(usernameInputField);
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameInputField)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputLabel))
                .addGap(18, 30, Short.MAX_VALUE)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton)
                    .addComponent(btnRegister))
                .addContainerGap())
        );

        loginButton.getAccessibleContext().setAccessibleName("loginButton");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        
        List<User> userList = DAOs.users
                .findByMail(usernameInputField.getText().toLowerCase());
        if (userList.isEmpty()) { 
            errorLabel.setText("Username not valid");
            usernameInputField.setForeground(Color.GRAY);
            usernameInputField.setText("name@example.com");
        } else {
            MPM.currentUser = userList.get(0);
            MPM.setPanel(new OverviewPanel());
            //System.out.println(MPM.currentUser.toString());
        }
        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void usernameInputFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameInputFieldFocusGained
        if (usernameInputField.getText().equals("name@example.com")) {
            usernameInputField.setText("");
            usernameInputField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_usernameInputFieldFocusGained

    private void usernameInputFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameInputFieldFocusLost
        if (usernameInputField.getText().isEmpty()) {
            usernameInputField.setForeground(Color.GRAY);
            usernameInputField.setText("name@example.com");
        }
    }//GEN-LAST:event_usernameInputFieldFocusLost

    private void usernameInputFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameInputFieldKeyPressed
        if (usernameInputField.getText().equals("name@example.com") 
                || usernameInputField.getText().equals("name@example.com ")) {
            usernameInputField.setText("");
            usernameInputField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_usernameInputFieldKeyPressed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        
        MPM.setPanel(new RegisterPanel());
    }//GEN-LAST:event_btnRegisterActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JTextField usernameInputField;
    // End of variables declaration//GEN-END:variables
}
