/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mpm.gui;

import mpm.main.MPM;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import mpm.data.dao.DAOs;
import mpm.data.entities.GeneralRole;

/**
 *
 * @author remo
 */
public class OverviewPanel extends javax.swing.JPanel {
    
    private ProjectListTab projectListTab;
    
    /**
     * Creates new form projectPanel
     */
    public OverviewPanel() {
        initComponents();
    
        ImageIcon projectsIcon = new ImageIcon(new ImageIcon(getClass()
                .getResource("/mpm/res/toolLogo.png"))
                .getImage().getScaledInstance(
                32, 32, Image.SCALE_DEFAULT));
            
        ImageIcon settingsIcon = new ImageIcon(new ImageIcon(getClass()
                .getResource("/mpm/res/settingsLogo.png"))
                .getImage().getScaledInstance(
                32, 32, Image.SCALE_DEFAULT));
        
        ImageIcon inventoryIcon = new ImageIcon(new ImageIcon(getClass()
                .getResource("/mpm/res/inventoryLogo.png"))
                .getImage().getScaledInstance(
                32, 32, Image.SCALE_DEFAULT));
        
        ImageIcon freeInfIcon = new ImageIcon(new ImageIcon(getClass()
                .getResource("/mpm/res/booking.png"))
                .getImage().getScaledInstance(
                32, 32, Image.SCALE_DEFAULT));
        
        ImageIcon techInfIcon = new ImageIcon(new ImageIcon(getClass()
                .getResource("/mpm/res/techInfLogo.png"))
                .getImage().getScaledInstance(
                32, 32, Image.SCALE_DEFAULT));
        
        // Icon for Request List
        ImageIcon requestListIcon = new ImageIcon(new ImageIcon(getClass()
                .getResource("/mpm/res/requestBellLogo.png"))
                .getImage().getScaledInstance(
                32, 32, Image.SCALE_DEFAULT));
        
        overviewTabbedPane.setIconAt(0, settingsIcon);
        
        GeneralRole currR = DAOs.roles.findByID(MPM.currentUser.getGeneralRoleId());
        
        nameLabel.setText(MPM.currentUser.getName());
        emailLabel.setText(MPM.currentUser.getEmail());
        roleLabel.setText(currR.getName());
        descriptionLabel.setText("(" + currR.getDescription() + ")");
        idLabel.setText("" + MPM.currentUser.getId());
        
        /*
            Parts dedicated to Makerspace technicians
        */
        
        boolean isUserStaff = DAOs.users.hasUserRole(MPM.currentUser, "Staff");
        
        projectListTab = new ProjectListTab(isUserStaff);
        overviewTabbedPane.insertTab("Projects", 
                    projectsIcon, projectListTab, "", 0);
        
        if (isUserStaff)
        { 
            overviewTabbedPane.insertTab("Inventory", 
                    inventoryIcon, new MaterialInventoryManagement(), "", 2);
            overviewTabbedPane.insertTab("Free Infs", 
                    freeInfIcon, new FreeInfManagement(), "", 3);
            overviewTabbedPane.insertTab("Technical Infs", 
                    techInfIcon, new TechInfManagement(), "", 4);
            overviewTabbedPane.insertTab("Requests", 
                    requestListIcon, new RequestsManagement(), "", 5);
        }
        
        overviewTabbedPane.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        overviewTabbedPane = new javax.swing.JTabbedPane();
        settingsTab = new javax.swing.JPanel();
        nameTitleLabel = new javax.swing.JLabel();
        emailTitleLabel = new javax.swing.JLabel();
        roleTitleLabel = new javax.swing.JLabel();
        idTitleLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        roleLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        updateProfileLabel = new javax.swing.JLabel();
        newEmailLabel = new javax.swing.JLabel();
        newEmailTextField = new javax.swing.JTextField();
        updateInformationButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(640, 480));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(640, 480));

        overviewTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        overviewTabbedPane.setMaximumSize(new java.awt.Dimension(635, 400));
        overviewTabbedPane.setMinimumSize(new java.awt.Dimension(600, 400));
        overviewTabbedPane.setPreferredSize(new java.awt.Dimension(600, 400));
        overviewTabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                overviewTabbedPaneStateChanged(evt);
            }
        });

        settingsTab.setPreferredSize(new java.awt.Dimension(526, 433));

        nameTitleLabel.setText("Name");

        emailTitleLabel.setText("Email");

        roleTitleLabel.setText("Role");

        idTitleLabel.setText("ID");

        nameLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        nameLabel.setText("jLabel9");

        emailLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        emailLabel.setText("jLabel10");

        roleLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        roleLabel.setText("jLabel11");

        descriptionLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        descriptionLabel.setText("jLabel12");

        idLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        idLabel.setText("jLabel13");

        updateProfileLabel.setText("Update Profile Information");

        newEmailLabel.setText("New email address");

        updateInformationButton.setText("Save");
        updateInformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInformationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout settingsTabLayout = new javax.swing.GroupLayout(settingsTab);
        settingsTab.setLayout(settingsTabLayout);
        settingsTabLayout.setHorizontalGroup(
            settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsTabLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateInformationButton)
                    .addComponent(updateProfileLabel)
                    .addGroup(settingsTabLayout.createSequentialGroup()
                        .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTitleLabel)
                            .addComponent(emailTitleLabel)
                            .addComponent(roleTitleLabel)
                            .addComponent(idTitleLabel))
                        .addGap(18, 18, 18)
                        .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idLabel)
                            .addGroup(settingsTabLayout.createSequentialGroup()
                                .addComponent(roleLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(emailLabel)
                            .addComponent(nameLabel)))
                    .addGroup(settingsTabLayout.createSequentialGroup()
                        .addComponent(newEmailLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(newEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        settingsTabLayout.setVerticalGroup(
            settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsTabLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTitleLabel)
                    .addComponent(nameLabel))
                .addGap(18, 18, 18)
                .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTitleLabel)
                    .addComponent(emailLabel))
                .addGap(18, 18, 18)
                .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roleTitleLabel)
                    .addComponent(roleLabel)
                    .addComponent(descriptionLabel))
                .addGap(18, 18, 18)
                .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTitleLabel)
                    .addComponent(idLabel))
                .addGap(114, 114, 114)
                .addComponent(updateProfileLabel)
                .addGap(18, 18, 18)
                .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newEmailLabel))
                .addGap(18, 18, 18)
                .addComponent(updateInformationButton)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        overviewTabbedPane.addTab("Profile", settingsTab);

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(overviewTabbedPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(overviewTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutButton)
                .addGap(27, 27, 27))
        );

        overviewTabbedPane.getAccessibleContext().setAccessibleName("Projects");
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        MPM.setPanel(new LoginPanel());
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void overviewTabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_overviewTabbedPaneStateChanged

        JTabbedPane e = (JTabbedPane)evt.getSource();

        if (e.getSelectedComponent().equals(projectListTab))
        {
            projectListTab.reloadProjectTable();
        }

    }//GEN-LAST:event_overviewTabbedPaneStateChanged

    private void updateInformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInformationButtonActionPerformed

        MPM.currentUser.setEmail(newEmailTextField.getText());

        try
        {
            DAOs.users.update(MPM.currentUser);
            emailLabel.setText(newEmailTextField.getText());
        }catch(RuntimeException ex){
            JOptionPane.showMessageDialog(this, "Oops, something went wrong. \n " + ex.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        JOptionPane.showMessageDialog(this, "Operation successful!");
        newEmailTextField.setText("");

    }//GEN-LAST:event_updateInformationButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailTitleLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idTitleLabel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameTitleLabel;
    private javax.swing.JLabel newEmailLabel;
    private javax.swing.JTextField newEmailTextField;
    private javax.swing.JTabbedPane overviewTabbedPane;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JLabel roleTitleLabel;
    private javax.swing.JPanel settingsTab;
    private javax.swing.JButton updateInformationButton;
    private javax.swing.JLabel updateProfileLabel;
    // End of variables declaration//GEN-END:variables
}
