/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mpm.gui;

import mpm.main.MPM;
import mpm.main.TestObject;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author remo
 */
public class OverviewPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form projectPanel
     */
    public OverviewPanel() {
        initComponents();

        
        ImageIcon projectsIcon = new ImageIcon(new ImageIcon(getClass().getResource("/mpm/res/toolLogo.png")).getImage().getScaledInstance(
            32, 32, Image.SCALE_DEFAULT));
            
        ImageIcon settingsIcon = new ImageIcon(new ImageIcon(getClass().getResource("/mpm/res/settingsLogo.png")).getImage().getScaledInstance(
                32, 32, Image.SCALE_DEFAULT));    
        
        overviewTabbedPane.setIconAt(0, projectsIcon);
        overviewTabbedPane.setIconAt(1, settingsIcon);
        
        ArrayList<ProjectListElement> list = new ArrayList<>();
        for(TestObject test : MPM.testList) {
            
            ProjectListElement e = new ProjectListElement(test);
            //e.titleLabel.setText(test.title);
            //e.descriptionLabel.setText(test.description);
            list.add(e);
        }
        for(ProjectListElement el : list){
            projectListPanel.add(el);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        overviewTabbedPane = new javax.swing.JTabbedPane();
        projectTab = new javax.swing.JPanel();
        projectScrollPane = new javax.swing.JScrollPane();
        projectListPanel = new javax.swing.JPanel();
        settingsTab = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(640, 480));

        overviewTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        projectScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        projectListPanel.setLayout(new javax.swing.BoxLayout(projectListPanel, javax.swing.BoxLayout.Y_AXIS));
        projectScrollPane.setViewportView(projectListPanel);

        javax.swing.GroupLayout projectTabLayout = new javax.swing.GroupLayout(projectTab);
        projectTab.setLayout(projectTabLayout);
        projectTabLayout.setHorizontalGroup(
            projectTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(projectScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        );
        projectTabLayout.setVerticalGroup(
            projectTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(projectScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        overviewTabbedPane.addTab("Projects", null, projectTab, "");

        settingsTab.setPreferredSize(new java.awt.Dimension(547, 473));

        logoutButton.setText("leave");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout settingsTabLayout = new javax.swing.GroupLayout(settingsTab);
        settingsTab.setLayout(settingsTabLayout);
        settingsTabLayout.setHorizontalGroup(
            settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        settingsTabLayout.setVerticalGroup(
            settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutButton)
                .addContainerGap(436, Short.MAX_VALUE))
        );

        overviewTabbedPane.addTab("Preferences", settingsTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(overviewTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(overviewTabbedPane)
        );

        overviewTabbedPane.getAccessibleContext().setAccessibleName("Projects");
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        
        MPM.setPanel(new LoginPanel());
    }//GEN-LAST:event_logoutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton logoutButton;
    private javax.swing.JTabbedPane overviewTabbedPane;
    private javax.swing.JPanel projectListPanel;
    private javax.swing.JScrollPane projectScrollPane;
    private javax.swing.JPanel projectTab;
    private javax.swing.JPanel settingsTab;
    // End of variables declaration//GEN-END:variables
}
