/*
 * Makerspace Project Management
 * Database Systems 2016-2017
 * Copyright 2016 (C) Grabocka Mikel, Nardini Matteo, Scolati Remo.
 * All rights reserved.
 */
package mpm.gui;

import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import mpm.data.dao.DAOs;
import mpm.data.entities.Purchase;
import mpm.main.MPM;

/**
 *
 * @author remo
 */
public class PurchaseHistoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form PurchaseHistoryPanel
     */
    public PurchaseHistoryPanel() {
        initComponents();
        
        List<Purchase> list = DAOs.purchases
                .findByProjectID(MPM.currentProject.getId());
        
        historyTable = new javax.swing.JTable();
        historyTable.setAutoCreateRowSorter(true);
        
        String[] columnNames = {"Material",
        "Price per unit",
        "Units",
        "Total Price"};
        
        DefaultTableModel model = new DefaultTableModel(0, columnNames.length);
        
        for(Purchase p : list){
            Object[] o = new Object[4];
            o[0] = "Mat Name";
            o[1] = (p.getTotalPrice().floatValue()/p.getUnits());
            o[2] = p.getUnits();
            o[3] = p.getTotalPrice().floatValue();
            
            model.addRow(o);
            System.out.println(o[0] + " " + o[1] + " " + o[2] + " " + o[3]);
        }
        
        historyTable.setModel(model);
        model.setColumnIdentifiers(columnNames);
        historyScrollPane.setViewportView(historyTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        historyScrollPane = new javax.swing.JScrollPane();
        historyTable = new javax.swing.JTable();

        historyTable.setAutoCreateRowSorter(true);
        historyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        historyScrollPane.setViewportView(historyTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(historyScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(historyScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane historyScrollPane;
    private javax.swing.JTable historyTable;
    // End of variables declaration//GEN-END:variables
}
