/*
 * Makerspace Project Management
 * Database Systems 2016-2017
 * Copyright 2016 (C) Grabocka Mikel, Nardini Matteo, Scolati Remo.
 * All rights reserved.
 */
package mpm.gui;

import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import mpm.data.dao.DAOs;
import mpm.data.entities.TechInf;
import mpm.data.logic.IDHider;

/**
 *
 * @author Shalen
 */
public class TechInfManagement extends javax.swing.JPanel {

    private TechInf selectedTechInf;
    
    /**
     * Creates new form TechInfManagement
     */
    public TechInfManagement() {
        initComponents();
        
        reloadTechInfList();
        tbTechInfs.getSelectionModel().addListSelectionListener(e -> {
            techInfListSelectionChanged();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbTechInfs = new javax.swing.JTable();
        pnlEditAdd = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        chbAvailable = new javax.swing.JCheckBox();
        btnSaveChanges = new javax.swing.JButton();
        btnAddNew = new javax.swing.JButton();

        jLabel3.setText("Current technical infrastructures:");

        tbTechInfs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Available"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbTechInfs.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tbTechInfs);

        pnlEditAdd.setBorder(javax.swing.BorderFactory.createTitledBorder("Edit selected:"));

        jLabel4.setText("Name:");

        jLabel8.setText("Available:");

        javax.swing.GroupLayout pnlEditAddLayout = new javax.swing.GroupLayout(pnlEditAdd);
        pnlEditAdd.setLayout(pnlEditAddLayout);
        pnlEditAddLayout.setHorizontalGroup(
            pnlEditAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditAddLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlEditAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditAddLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(58, 58, 58))
                    .addGroup(pnlEditAddLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(42, 42, 42)))
                .addGroup(pnlEditAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbAvailable)
                    .addComponent(txtName))
                .addGap(20, 20, 20))
        );
        pnlEditAddLayout.setVerticalGroup(
            pnlEditAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditAddLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlEditAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEditAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(chbAvailable))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnSaveChanges.setText("Save changes");
        btnSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveChangesActionPerformed(evt);
            }
        });

        btnAddNew.setText("Add new");
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlEditAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSaveChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlEditAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveChangesActionPerformed

        if (btnSaveChanges.getText().endsWith("Save changes"))
        {
            if (selectedTechInf == null)
            {
                JOptionPane.showMessageDialog(this, "Select a techinical infrastructure to edit", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            selectedTechInf.setName(txtName.getText());
            selectedTechInf.setAvailable(chbAvailable.isSelected());

            try
            {
                DAOs.technical_infs.update(selectedTechInf);
                reloadTechInfList();
                tbTechInfs.getSelectionModel().setSelectionInterval(0, 0);
            }catch(RuntimeException ex){
                JOptionPane.showMessageDialog(this, "Oops, something went wrong. \n " + ex.getMessage(), 
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            JOptionPane.showMessageDialog(this, "Operation successful!");
            return;
        }

        if (btnSaveChanges.getText().endsWith("Abort creation"))
        {
            ((TitledBorder) pnlEditAdd.getBorder()).setTitle("Edit selected:");
            pnlEditAdd.repaint();
            tbTechInfs.getSelectionModel().setSelectionInterval(0, 0);
            btnAddNew.setText("Add new");
            btnSaveChanges.setText("Save changes");
        }

    }//GEN-LAST:event_btnSaveChangesActionPerformed

    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed

        if (btnAddNew.getText().equals("Add new"))
        {
            ((TitledBorder) pnlEditAdd.getBorder()).setTitle("New technical infrastructure:");
            pnlEditAdd.repaint();
            tbTechInfs.getSelectionModel().clearSelection();
            btnAddNew.setText("Save new");
            btnSaveChanges.setText("Abort creation");
            return;
        }

        if (btnAddNew.getText().equals("Save new"))
        {
            if (txtName.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, "Add a name for the new technical infrastructure", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            TechInf ti = new TechInf(DAOs.technical_infs.getNextValidId());
            ti.setName(txtName.getText());
            ti.setAvailable(chbAvailable.isSelected());
            
            try
            {
                DAOs.technical_infs.insert(ti);
                reloadTechInfList();
                tbTechInfs.getSelectionModel().setSelectionInterval(0, 0);

                btnAddNew.setText("Add new");
                btnSaveChanges.setText("Save changes");
                ((TitledBorder) pnlEditAdd.getBorder()).setTitle("Edit selected:");
            }catch(RuntimeException ex){
                JOptionPane.showMessageDialog(this, "Oops, something went wrong. \n " + ex.getMessage(), 
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            JOptionPane.showMessageDialog(this, "Operation successful!");
        }

    }//GEN-LAST:event_btnAddNewActionPerformed

    private void reloadTechInfList()
    {
        DefaultTableModel m = (DefaultTableModel) tbTechInfs.getModel();
        m.setRowCount(0);
        
        DAOs.technical_infs.getAll().forEach(t -> {
            Object[] a = new Object[2];
            a[0] = new IDHider(t, t.getName()); 
            a[1] = t.getAvailable();
            
            m.addRow(a);
        }); 
    }
    
    private void techInfListSelectionChanged()
    {
        int selectedIndex = tbTechInfs.getSelectedRow();
        if (selectedIndex == -1)
        {
            txtName.setText("");
            chbAvailable.setSelected(false);
            return;
        }

        TableModel m = tbTechInfs.getModel();
        selectedTechInf = ((IDHider<TechInf>) m.getValueAt(selectedIndex, 0)).getHidden();
        
        txtName.setText(selectedTechInf.getName());
        chbAvailable.setSelected(selectedTechInf.getAvailable());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnSaveChanges;
    private javax.swing.JCheckBox chbAvailable;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlEditAdd;
    private javax.swing.JTable tbTechInfs;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
