/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mpm.gui;

import java.awt.*;
import javax.swing.*;
import mpm.data.entities.Project;
import mpm.main.MPM;

/**
 *
 * @author remo
 */
public class UserListElement extends javax.swing.JPanel {
    
    /**
     * Creates new form ProjectListElement
     */
    public UserListElement(String userName, String userGeneralRole, 
            String userEmail, String userRole) {
        initComponents();
        
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(
                getClass().getResource("/mpm/res/personLogo.png"))
                .getImage().getScaledInstance(
                        76, 76, Image.SCALE_DEFAULT));
        
        imageLabel.setIcon(imageIcon);
        emailLabel.setText(userEmail);
        userNameLabel.setText(userName);
        generalRoleLabel.setText(userGeneralRole);
        if(userRole.equals("ADMINISTRATOR")){
            roleLabel.setForeground(Color.green);
            roleLabel.setText("Administrator");
        }else{
            roleLabel.setText("Collaborator");
        }
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        roleLabel = new javax.swing.JLabel();
        roleTitleLabel = new javax.swing.JLabel();
        emailTitleLabel = new javax.swing.JLabel();
        generalRoleLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(450, 100));
        setMinimumSize(new java.awt.Dimension(450, 100));
        setPreferredSize(new java.awt.Dimension(450, 100));

        userNameLabel.setText("jLabel1");

        emailLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        emailLabel.setText("jLabel1");

        roleLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        roleLabel.setText("jLabel1");

        roleTitleLabel.setText("Role");

        emailTitleLabel.setText("Email");

        generalRoleLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        generalRoleLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(roleTitleLabel)
                                .addGap(33, 33, 33)
                                .addComponent(roleLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(emailTitleLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(emailLabel)))
                        .addGap(281, 281, 281))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generalRoleLabel)
                        .addGap(107, 107, 107))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userNameLabel)
                            .addComponent(generalRoleLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emailTitleLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roleLabel)
                            .addComponent(roleTitleLabel))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailTitleLabel;
    private javax.swing.JLabel generalRoleLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JLabel roleTitleLabel;
    public javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
