/* 
 * File clean.sql
 * Resets the database to an empty state.
 * Group members: 
 * 		Remo Scolati: 	remo_scolati@hotmail.com
 * 		Mikel Grabocka: mgrabocka@unibz.it
 * 		Matteo Nardini: mnardini@unibz.it
 */

-- Should work as is 
 
DROP TABLE IF EXISTS PURCHASE CASCADE;
DROP TABLE IF EXISTS BOOKING CASCADE;
DROP TABLE IF EXISTS PARTICIPATION CASCADE;
DROP TABLE IF EXISTS PROJECT CASCADE;
DROP TABLE IF EXISTS MAKERSPACE_USER CASCADE;
DROP TABLE IF EXISTS GENERAL_ROLE CASCADE;
DROP TABLE IF EXISTS FREE_INFRASTRUCTURE CASCADE;
DROP TABLE IF EXISTS TECHNICAL_INF CASCADE;
DROP TABLE IF EXISTS REQUEST CASCADE;
DROP TABLE IF EXISTS MESSAGE CASCADE;
DROP TABLE IF EXISTS MATERIAL CASCADE;
